"""Weather API routes for MeshCenter."""

from __future__ import annotations

import os
import re
import tempfile

from flask import jsonify, request


_API_KEY_PATTERN = re.compile(r"^[A-Za-z0-9_-]{20,128}$")

# One secret variable per provider id, all kept in the same weather_secrets.py
# file - see _save_weather_secret(), which preserves whichever ones it isn't
# currently updating.
_SECRET_VAR_NAMES = {
    "openweather": "OPENWEATHER_API_KEY",
    "weatherapi": "WEATHERAPI_API_KEY",
}

# Provider website links for the "Live · <Provider>" badge. The display
# name itself comes from each WeatherProvider's own display_name attribute
# (weather/providers/*.py) rather than being duplicated here - only the
# website URL isn't part of that existing interface.
_PROVIDER_URLS = {
    "openweather": "https://openweathermap.org",
    "weatherapi": "https://www.weatherapi.com",
}


def _normalize_api_key(value):
    key = str(value or "").strip()
    if not key:
        return ""
    if not _API_KEY_PATTERN.fullmatch(key):
        return ""
    return key


def _read_existing_secrets(path):
    """Best-effort read of the keys currently saved in weather_secrets.py, so
    saving one provider's key doesn't clobber another provider's already-saved
    key."""
    values = {name: "" for name in _SECRET_VAR_NAMES.values()}
    try:
        with open(path, "r", encoding="utf-8") as handle:
            content = handle.read()
    except OSError:
        return values

    for var_name in values:
        match = re.search(rf'^{var_name}\s*=\s*"([^"]*)"', content, re.MULTILINE)
        if match:
            values[var_name] = match.group(1)
    return values


def _save_weather_secret(path, provider_id, api_key):
    """Write one provider's API key atomically, preserving other providers'
    keys already saved in the same file, and keep the secret file private."""
    path = os.path.abspath(path)
    directory = os.path.dirname(path)
    os.makedirs(directory, exist_ok=True)

    var_name = _SECRET_VAR_NAMES[provider_id]
    values = _read_existing_secrets(path)
    values[var_name] = api_key

    lines = [f'{name} = "{value}"' for name, value in values.items()]
    content = (
        '"""Local weather provider secrets. Generated by MeshCenter.\n'
        "Do not commit this file to Git.\n"
        '"""\n\n'
        + "\n".join(lines) + "\n"
    )

    fd, temporary_path = tempfile.mkstemp(
        prefix=".weather_secrets.",
        suffix=".tmp",
        dir=directory,
        text=True,
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary_path, 0o600)
        os.replace(temporary_path, path)
        os.chmod(path, 0o600)
    finally:
        if os.path.exists(temporary_path):
            os.unlink(temporary_path)


def register_weather_routes(
    app,
    weather_manager,
    resolve_location=None,
    secrets_path=None,
):
    def resolved_location():
        location = resolve_location() if callable(resolve_location) else None
        return location if isinstance(location, dict) else {}

    @app.get("/api/weather/current")
    def api_weather_current():
        force = request.args.get("refresh", "").lower() in {"1", "true", "yes"}
        location = resolved_location()

        payload = weather_manager.active().get_current(
            force=force,
            latitude=location.get("latitude"),
            longitude=location.get("longitude"),
            location_name=location.get("name", ""),
            location_source=location.get("source", "configured"),
        )
        active_id = weather_manager.active_id
        payload["provider"] = {
            "id": active_id,
            "name": weather_manager.active().display_name,
            "url": _PROVIDER_URLS.get(active_id, "#"),
        }
        return jsonify(payload), 200 if payload.get("ok") else 503

    @app.get("/api/weather/config")
    def api_weather_config_status():
        return jsonify({
            "ok": True,
            "provider": weather_manager.active_id,
            "configured": weather_manager.active().is_configured(),
        })

    @app.post("/api/weather/config")
    def api_weather_save_key():
        data = request.get_json(silent=True) or {}
        api_key = _normalize_api_key(data.get("api_key"))
        if not api_key:
            return jsonify({
                "ok": False,
                "error": "Enter a valid API key.",
            }), 400

        provider = weather_manager.active()
        location = resolved_location()
        test_result = provider.test_api_key(
            api_key,
            latitude=location.get("latitude"),
            longitude=location.get("longitude"),
        )
        if not test_result.get("ok"):
            return jsonify(test_result), 400

        if not secrets_path:
            return jsonify({
                "ok": False,
                "error": "Weather secret storage is not configured.",
            }), 500

        try:
            _save_weather_secret(secrets_path, weather_manager.active_id, api_key)
            provider.set_api_key(api_key)
        except OSError as exc:
            print(f"[WEATHER] Could not save API key: {exc}", flush=True)
            return jsonify({
                "ok": False,
                "error": "Could not save the API key.",
            }), 500

        return jsonify({
            "ok": True,
            "configured": True,
            "provider": weather_manager.active_id,
            "message": "API key saved successfully.",
        })
